version: '2.1'
services:
    letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS},
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
      - DHLEVEL=${DHLEVEL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - STAGING=${STAGING}
    networks:
      cybererp-network:
        aliases:
          - letsencrypt
    volumes:
      - ./conf/proxy/odoo.conf:/config/nginx/proxy-confs/odoo.subdomain.conf
      - ./conf/proxy/pgadmin.conf:/config/nginx/proxy-confs/pgadmin.subdomain.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
  postgresql:
    image: postgres:10
    container_name: postgresql
    hostname: postgresql
    environment:
       - POSTGRES_DB=${POSTGRES_DB}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_USER=${POSTGRES_USER}
       - PGDATA=${PGDATA}
    networks:
      cybererp-network:
        aliases:
          - postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data/pgdata
    restart: always
  odoo:
    image: odoo:12.0
    container_name: odoo
    hostname: odoo
    # command: --database odoo -i base
    environment:
      - HOST=postgresql
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASSWORD}
    networks:
      cybererp-network:
        aliases:
          - odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./conf/odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - postgresql
      - letsencrypt
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    # ports:
    #  - "10080:80"
    depends_on:
      - postgresql
    networks:
      cybererp-network:
        aliases:
         - pgadmin
    restart: always
volumes:
  postgresql_data:
  odoo_data: 
networks:
  cybererp-network:
    driver: bridge
